### ISSUE TITLE
Authentication using WebID

### ISSUE THREAD

**Issue by ChristiaanScheermeijer** [trompamusic/ce-api#105]
As discussed in https://github.com/trompamusic/ce-api/pull/98#discussion_r392920415 it is difficult for front-end only applications to create a JWT token. 

We should figure out if we can create a solution to generate tokens using the [WebID protocol](https://www.w3.org/wiki/WebID) proposed by @musicog.

**Comment by musicog** [comment]
Perhaps informative: https://github.com/solid/webid-oidc-spec

**Comment by baukef** [comment]
@ChristiaanScheermeijer can you explain what the current status of the implementation is and this related to this feature request?

**Comment by ChristiaanScheermeijer** [comment]
@baukef We've implemented Authentication according to the following [documentation](https://github.com/trompamusic/ce-api/blob/staging/docs/authentication.md). Since this feature is an extension to the currently available authentication mechanism, we should decide to skip this for now.

**Comment by baukef** [comment]
Ok, lets close this issue for now.

**Comment by musicog** [comment]
I believe we now have suitable authentication mechanisms in place for both web-app => Solid and CE (TPL) => Solid interactions. Per Bauke's comment, closing for now.
