### ISSUE TITLE
RequestControlAction returns SERVER Error if Entrypoint node does not exist

### ISSUE THREAD

**Issue by aggelosgkiokas** [trompamusic/ce-api#129]
mutation 	RequestControlAction returns INTERNAL_SERVER_ERROR if entryPointIdentifier does not exist. It should return something like an empty result

**Comment by alastair** [comment]
This happens not only if the entryPointIdentifier does not exist, but also if the potentialActionPropertyIdentifier or nodeIdentifier or potentialActionPropertyValueSpecificationIdentifier doesn't exist.
