### ISSUE TITLE
Use PropertyValueSpecification.defaultValue in RequestControlAction

### ISSUE THREAD

**Issue by alastair** [trompamusic/ce-api#144]
if there is a PropertyValueSpecification that has a defaultValue set, and this Property is not specified in the `propertyValueObject` section of the `RequestControlAction` mutation, then a PropertyValue should still be created with the default value.

**Comment by alastair** [comment]
Additional question - if a PropertyValueSpecification is required, but has a defautlValue, should it be required to set a value in RequestControlAction?

**Comment by alastair** [comment]
Our proposed behaviour is:

* valueRequired: false, defaultValue: ‘low priority’, inputValue: undefined = use default value
* valueRequired: false, defaultValue: ‘low priority’, inputValue: ‘high priority’ = use input value
* valueRequired: true, defaultValue: ‘low priority’, inputValue: undefined = use default value
* valueRequired: true, defaultValue: ‘low priority’, inputValue: ‘high priority’ = use input value
* valueRequired: true, defaultValue: undefined, inputValue: undefined = error!
* valueRequired: true, defaultValue: undefined, inputValue: ‘low priority’ = use input value

**Comment by aggelosgkiokas** [comment]
I would decouple this from the target values range, and define this for any x,y. I.e.

valueRequired: false, defaultValue: x, inputValue: missing = return x
valueRequired: false, defaultValue: x, inputValue: y = return y
valueRequired: false, defaultValue: undefined, inputValue: undefined = error / or don't create node (TBD)
valueRequired: false, defaultValue: undefined, inputValue: y = return y
valueRequired: true, defaultValue: x, inputValue: missing = return x
valueRequired: true, defaultValue: x, inputValue: y = return y
valueRequired: true, defaultValue: undefined, inputValue: missing = error / or don't create node (TBD)
valueRequired: true, defaultValue: undefined, inputValue: y = return y / or error (TBD)
