### ISSUE TITLE
MusicComposition has author and composer fields but only author can be filled in

### ISSUE THREAD

**Issue by alastair** [trompamusic/ce-api#18]
You can join a `CreativeWork` and `Person` with `AddCreativeWorkInterfaceLegalPerson`, as long as one of the fields is a `CreativeWorkInterfaceRelationToLegalPerson`

Some objects such as `MusicComposition` have more specific fields that have a clearer semantic meaning, such as `composer` (instead of `author`). There's no mutation to add this field, and it'd be nice to be able to have to join objects in the database with a more semantically correct link.

**Comment by ChristiaanScheermeijer** [comment]
This is solved by #48
