### ISSUE TITLE
Can query compositions by creator string but not Person object

### ISSUE THREAD

**Issue by alastair** [trompamusic/ce-api#20]
Among other fields, a `MusicComposition` query can be filtered by the `creator` field, which is a text string on the MusicComposition object:
```
query {
  MusicComposition(creator: "Ralph Vaughan Williams") {
  }
}
```
However we also have an author of a composition, linked using the `AddCreativeWorkInterfaceLegalPerson` mutation.
I'd like to be able to query all compositions given a person's identifier. This would help us avoid the issue where different sources name a person slightly differently, or two people have the same name.

**Comment by ChristiaanScheermeijer** [comment]
With #48 there are now filters for all queries. However, I see that for interfaced relations there are no filters generated.

The following query works:

```graphql
query {
  MusicComposition(filter: { lyricist: { identifier: "id"} }) {
    identifier
  }
}
```

But `composer` will not:

```graphql
query {
  MusicComposition(filter: { composer: { identifier: "id" } }) {
    identifier
  }
}
```

I will have to dive into the neo4j-graphql-js library to see what the problem is.

**Comment by alastair** [comment]
With https://github.com/trompamusic/ce-api/pull/133 we fixed this by adding a relation explicitly to the concrete type that we wanted to filter by.
Do we still have a need to filter by the compose of a MusicComposition? If so, we should add this relationship here too

**Comment by ChristiaanScheermeijer** [comment]
@alastair can this issue be closed?

**Comment by alastair** [comment]
This filter works for me on my local CE, so I guess everything is fine!
```
query {
  MusicComposition(filter:{composer:{identifier:"c6b208e0-61d8-47e7-8555-6360c6cd3612"}}) {
    identifier
    title
    composer {
      ... on Person {
        name
        identifier
      }
    }
  }
}
```
