### ISSUE TITLE
ThingInterface does not have contentUrl

### ISSUE THREAD

**Issue by aggelosgkiokas** [trompamusic/ce-api#204]
In the modelling discussion, for AudioObject, MediaObject and VideoObject, the URI of the object is contained in the contentURL feld. 

However, for requesting a ControlAction, it is impossible to access this field, because the the PropertyValue nodes do not support this.

PropertyValue --> NodeValue implements ThingInterface. ThingInterface does not have contentURL field.

Could be a solution to just add the contentUrl field in ThingInterface??

**Comment by alastair** [comment]
Unfortunately we can't put contentUrl in ThingInterface, because it means that all objects that implement ThingInterface would have to add it, and that doesn't make sense.

Can you perform a query like this?

```
nodeValue {
    identifier
    ... on AudioObject {
        contentUrl
    }
}
```

**Comment by aggelosgkiokas** [comment]
works. thanks
