### ISSUE TITLE
can query one-to-many fields in the one direction, but not the many direction

### ISSUE THREAD

**Issue by alastair** [trompamusic/ce-api#21]
I create a `Person` (composer) and `MusicComposition` (work), joined with `AddCreativeWorkInterfaceLegalPerson` field: author, and then a `DigitalDocument` (score), joined to the work with `AddThingInterfaceCreativeWorkInterface` field: subjectOf.

I can query a document and get its work, and also get the work's author:
```
query {
  DigitalDocument(source:"https://www.cpdl.org/wiki/images/b/b2/El_Rossinyol.mxl") {
    name
    identifier
    relation
    subjectOf {
      ... on MusicComposition {
        name
        source
        author {
          ... on Person {
            identifier
            name
            source
          }
        }
      }
    }
  }
}
```

However, I'd also like to be able to do the reverse, e.g. given a Person, list all of the MusicCompositions that they wrote, or given a MusicComposition, get all of the scores that it has. Looking through the schema, I can't find a way of performing these "reverse" lookups.

**Comment by alastair** [comment]
Looking into this, I see that the inverse of the subjectOf property is about:
https://schema.org/subjectOf
https://schema.org/about

I can get this inverse relationship to work by changing the definition of MusicComposition.about:
https://github.com/trompamusic/ce-api/blob/5850b5440d2df9536f539836d3acd443363a3c33/src/schema/type/MusicComposition.graphql#L86
from `about: [ThingInterfaced] @relation(name: "ABOUT", direction: "OUT")`
to `about: [ThingInterfaced] @relation(name: "SUBJECT_OF", direction: "IN")`

However we should decide how we want to implement this in the database:
  * Require users to add both a _subjectOf_ and an _about_ relation (there's currently no mutation for _about_)
 * When _subjectOf_ or _about_ is added, automatically add the inverse as well
 * This suggested change, only include _subjectOf_, and use the reverse of this relationship for _about_

---

The same question is posed for the author of a composition. What would the relation be to ask for all of the compositions of a person?

**Comment by ChristiaanScheermeijer** [comment]
Hi @alastair,

I like the last suggestion. You shouldn't have to add relations twice if it is an inverse property.

**Comment by alastair** [comment]
I've already done this here: https://github.com/trompamusic/ce-api/pull/36, so I think we can close this and use this as the process from now on.
It looks to me like all of these fields may have been generated, and (almost) all of them have direction: "OUT". Do we want to change them to IN where needed when we see that the relationship exists, or should we go and audit all fields and fix them all in a single batch?

**Comment by ChristiaanScheermeijer** [comment]
I'd prefer to audit all fields and change them in a single batch. 

Regarding your question: `What would the relation be to ask for all of the compositions of a person?`

I see there is no reverse property for the [composer](https://schema.org/composer) property. However, with the neo4j-graphql-js update this can be achieved by using the following query:

```
query {
  MusicCompositions(filter: { composer: { identifier: "id" } }) {
    identifier
    name
  }
}
```

You can also query for the `name` property like so:

```
query {
  MusicCompositions(filter: { composer: { name_contains: "mahler" } }) {
    identifier
    name
  }
}
```

**Comment by alastair** [comment]
One of the key features that graphql says is an advantage of their tool is that you can ask specifically for the data that you need, and get the data back in a single response. If we need to do multiple requests then we may as well use a REST API.

We should confirm with @musicog how we should model person / composition objects and what the field values should be. It's possible that there are some additional models that make this kind of relationship easier to model.

**Comment by ChristiaanScheermeijer** [comment]
> One of the key features that graphql says is an advantage of their tool is that you can ask specifically for the data that you need, and get the data back in a single response. If we need to do multiple requests then we may as well use a REST API.

You mean if you want to query all composers and also get all of the related compositions? For example like so:

```
query {
  Persons(filter: { jobTitle: "composer" }) {
    identifier
    name
    compositions {
      identifier
      name
    }
  }
}
```

**Comment by alastair** [comment]
yes, right. it would be great to be able to get all related information like this in a single query.

**Comment by ChristiaanScheermeijer** [comment]
@musicog do you have a suggestion regarding:

> We should confirm with @musicog how we should model person / composition objects and what the field values should be. It's possible that there are some additional models that make this kind of relationship easier to model.

**Comment by alastair** [comment]
I think this is fine now, when I opened the ticket I didn't know about the `filter: ` syntax.
