### ISSUE TITLE
Allow non-exact dates

### ISSUE THREAD

**Issue by alastair** [trompamusic/ce-api#22]
We have some data that has a non-exact date, e.g. for a composer, Born: circa 1860, Died: circa 1920.
This information should be able to be stored in the CE.

**Comment by ChristiaanScheermeijer** [comment]
@alastair do you have a suggestion about how this data could be stored?

**Comment by alastair** [comment]
@musicog might have some ideas about how these kinds of dates are normally stored in linked data

**Comment by musicog** [comment]
Sorry for the delayed response, I missed this originally.

Unfortunately I don't have any satisfying response here -- approximate / uncertain dates are still somewhat an open problem for Linked Data; and it's a big problem, particularly in early publishing. 

In a previous project around publishing the Early English Books Online (EEBO) corpus as Linked Data, we ended up defining our own precise- and exact- properties, e.g. eeboo:precise-birth and eeboo:precise-death for birth and death dates; see https://github.com/oerc-elephat/preprocessed-elephant/blob/master/eeboo-ontology.ttl

What makes it more difficult is that different data sets have a huge variety of ways of expressing precise and approximate dates -- here's the (large) set of regular expressions we wrote to capture them from the EEBO corpus (p == precise, a == approximate, r == range)
https://github.com/oerc-elephat/preprocessed-elephant/blob/master/regex-author-year.csv
https://github.com/oerc-elephat/preprocessed-elephant/blob/master/regex-publication-date.csv

The other approach is to cheat -- e.g., dbpedia does things like specifying "1551-0-0" to mean "sometime in the year 1551", see the death date for Richard Sherry on this page: http://dbpedia.org/page/Richard_Sherry

Ideally, this is something that we should think about carefully, with input from a (music) domain expert.

**Comment by ChristiaanScheermeijer** [comment]
Duplicate #91

**Comment by alastair** [comment]
Not quite the same, #91 talks about "Born in 1790-04, but we don't know the day", and this one is "Born some time around 1790 (maybe some years before or after)", but I agree that they're closely related and we could track them in one ticket. If we do so, we should add notes from this ticket to the other one.
