### ISSUE TITLE
Definitions for ControlAction actionStatus

### ISSUE THREAD

**Issue by alastair** [trompamusic/ce-api#29]
The documentation for ControlAction.actionStatus says that it's based on schema.org/actionStatus:

https://github.com/trompamusic/ce-api/blob/2cd07c898c56da245743aa3c2338cc56f40ac8c4/src/schema/type/ControlAction.graphql#L56

However, schema.org only defines 4 statuses, and there are 8 in the CE. It'd be good to have some additional documentation which describes which ones are additional, and their meaning.

**Comment by ChristiaanScheermeijer** [comment]
I see the statuses are totally different from the statuses defined in the schema.org definition. Would we like to align these?

- ActiveActionStatus
- CompletedActionStatus
- FailedActionStatus
- PotentialActionStatus

**Comment by alastair** [comment]
I think we are probably OK with just the schema.org values. I don't see a requirement for the "intermediate" values in the current enum.
