### ISSUE TITLE
Storing semantic information in graphql documentation

### ISSUE THREAD

**Issue by alastair** [trompamusic/ce-api#30]
In the json-ld patch, we're using the semantic web properties from the graphql schema to define the format of the output. Copying [a comment of mine](https://github.com/trompamusic/ce-api/pull/23#discussion_r320147710) here for further discussion so that we can merge json-ld as-is. 

I don't like the idea of repurposing the documentation/description fields of the schema to provide semantic meaning. It means that we lose the ability to add documentation here to explain what a field is for and what data to put into it (I'd prefer documentation in the schema rather than a separate document). I also worry that parsing this field could cause problems if bad data is added.
While it would be a bit more work, what about a separate file that provides this mapping? It could be as simple as a json document like {"Model": {"field": "schema"}} that we read and parse on startup. A downside of this is that we make a separation of the schema and mapping, which means that we have to remember to update data in two places when we make a change.

**Comment by baukef** [comment]
Deadline M23.5
