### ISSUE TITLE
Decide what precision of integers we need for the API

### ISSUE THREAD

**Issue by alastair** [trompamusic/ce-api#32]
Continuing on from https://github.com/trompamusic/ce-api/pull/23#discussion_r319992632

Neo4j supports 64 bit integers, but javascript only supports 53 bit, so the neo4j client for js has its own Integer class which includes "low" bits and "high" bits. These methods have a toInt() method (to make a js int, for values < 2^53-1) or toString() to represent the number as a string: https://github.com/neo4j/neo4j-javascript-driver#numbers-and-the-integer-type
This means that when we process these values in js (for example in the REST endpoint for json-ld), we get the Integer objects:
![Screenshot 2019-10-09 at 4 18 45 PM](https://user-images.githubusercontent.com/19217/66489857-8f402480-eab0-11e9-9dbc-a5be4439afd4.png)
Although it's worth pointing out that the graphql wrapper turns this back into a "normal" integer:
![Screenshot 2019-10-09 at 4 18 30 PM](https://user-images.githubusercontent.com/19217/66489897-9f580400-eab0-11e9-8071-3795807b1a26.png)

If we find the low/high in JS to be difficult to work with, we can set the `disableLosslessIntegers` option in the neo4j connector to disable it, otherwise we should document the places in JS that we use this well enough to make sure that everyone knows to use toInt or toString as necessary.

**Comment by ChristiaanScheermeijer** [comment]
Hi @alastair,

Just checking, if we change this in the next version, will this break any existing implementation?

**Comment by alastair** [comment]
I don't think it'll break anything. What way do you think you'll fix it? By making all fields integers, making all fields strings, or changing their behaviour to be integer up to 2^53-1 and string afterwards?
All of our integers until now are very small (e.g. < 1000), so we definitely don't have a problem using integers at the moment. I really don't see a chance of us having numbers over 9007199254740992!

**Comment by ChristiaanScheermeijer** [comment]
> All of our integers until now are very small (e.g. < 1000), so we definitely don't have a problem using integers at the moment. I really don't see a chance of us having numbers over 9007199254740992!

Me neither, I think it's safe enough to enable native numbers in Neo4j. Agreed?

https://github.com/neo4j/neo4j-javascript-driver#enabling-native-numbers

**Comment by alastair** [comment]
sounds good to me
