### ISSUE TITLE
_ThingInterfaceInput definition is missing fields

### ISSUE THREAD

**Issue by alastair** [trompamusic/ce-api#39]
I'm running into a really weird issue which I'm unable to get my head around:

I rebuilt the Docker image with node 10.13's debian package in order to do some debugging. While running the Algorithm runner mutations, I received an error from the CE:

 > Field "type" is not defined by type _ThingInterfaceInput.

Looking at the docs/schema in the web interface, I see that this input is missing the `type` field:

![Screenshot 2019-11-28 at 1 41 28 PM](https://user-images.githubusercontent.com/19217/69807135-d90dd700-11e4-11ea-987d-35005507c48b.png)

But the field is definitely defined in the staging branch: https://github.com/trompamusic/ce-api/blob/5cf6e67c311d0d4e4e9b94d8a4c8a98f281d717b/src/schema/input.graphql#L3

Returning to the original -alpine image that I was using, this type correctly had the identifier and type fields.

At first I thought that there might have been old code from a previous time that I rebuilt the image, so I cleared all of my CE containers/images and rebuilt, but the field is still missing.

I'm able to edit the `input.graphql` file and add more input types, and they show up correctly in the web interface, including a new type which has this `type` field!:

![Screenshot 2019-11-28 at 1 45 04 PM](https://user-images.githubusercontent.com/19217/69807316-4ae62080-11e5-11ea-83e9-f83203efebf5.png)

However, if I try and add any more fields to the `_ThingInterfaceInput` type, none of them appear:

![Screenshot 2019-11-28 at 1 45 46 PM](https://user-images.githubusercontent.com/19217/69807426-8b459e80-11e5-11ea-98b6-13173ab2f7ae.png)

Other input types such as `_LegalPersonInput` correctly have identifier and type fields.
I thought that perhaps it could be something to do with being the first item in the file, but I moved it around and it still doesn't work. Only the `_ThingInterfaceInput` type is missing fields.

Any idea what the cause of this issue may be? Perhaps a recent upgrade to Apollo or the neo4j interface?

**Comment by alastair** [comment]
Looking into these types in more detail, I see other issues:

`_PropertyInput`, `_PropertyValueInput` and `_OrganizationInterfaceInput` don't show all defined fields, in the same way as `_ThingInterfaceInput`

_ProvenanceActivityInterfaceInput is defined:
![Screenshot 2019-11-28 at 1 52 48 PM](https://user-images.githubusercontent.com/19217/69807763-6140ac00-11e6-11ea-88de-60fbc15ad898.png)
but shows as
![Screenshot 2019-11-28 at 1 53 06 PM](https://user-images.githubusercontent.com/19217/69807779-6aca1400-11e6-11ea-8d12-d4a942f15a48.png)

**Comment by alastair** [comment]
I've tracked the cause of this down to the same issue as #16 
Because we still don't include package-lock.json in the Dockerfile, npm installs the latest version of some packages. For example, 

```
     "neo4j-graphql-js": {
-      "version": "2.4.2",
+      "version": "2.9.3",
```

It's possible that something important has changed in neo4j-graphql-js since then (https://github.com/neo4j-graphql/neo4j-graphql-js/blob/master/CHANGELOG.md, since the issue is with generating the schema from the definition files I'm assuming that this is the package which is causing the problem). It's possible that we need to upgrade some dependencies.
In the meantime, we really need to get package-lock.json into the Dockerfile to prevent these kind of issues from happening again.

**Comment by alastair** [comment]
Do we want to look at upgrading some dependencies for the CE as well? To be from 2.4 -> 2.9 is quite a gap. I worry that if we don't upgrade it will become even more difficult in the future.

**Comment by baukef** [comment]
@VincentCouzij is working on that right now!
