### ISSUE TITLE
Review required fields

### ISSUE THREAD

**Issue by alastair** [trompamusic/ce-api#44]
Some fields are required on ThingInterface (name, description), which makes them required on all items. Sometimes we find that we don't have useful information for some of these fields.
In addition, many types also have a title field, which is often required too. In the case where both name and title are required, should we make name non-required?

**Comment by ChristiaanScheermeijer** [comment]
@alastair is it correct that the Dublin Core [title](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/2012-06-14/?v=elements#title) property has the same meaning as the schema.org [name](https://schema.org/name) property? If so, shouldn't we make this into a single property? 

```
  "https://schema.org/name,http://purl.org/dc/elements/1.1/title"
  name: String!
```

Although, after that change, the property name doesn't match, the JSON-LD converter should convert the above schema into:

```
  "name": "Gustav Mahler",
  "dc:title": "Gustav Mahler",
```

**Comment by alastair** [comment]
@musicog please confirm if what Christiaan says is correct

**Comment by musicog** [comment]
In general, the DCMI's (experimental, proposed) mappings to schema.org model dc:title as a sub property of schema:name, which makes intuitive sense to me. I.e., they are related, but not equivalent, with title being a narrower / more constrained name. 

Whether this mismatch will lead to any problems in our case remains to be discussed; consider for example the Wikipedia article https://en.wikipedia.org/wiki/Johann_Ernst_Bach_(musician_at_Saxe-Weimar) which arguably ought to have schema:name "Johann Ernst Bach" and dc:title "Johann Ernst Bach (musician at Saxe-Weimar).

**Comment by alastair** [comment]
Does that solve our specific problem? In the case of name/title I guess we have the following options:
 * make one or both of title and name optional
 * make name and title the same field
 * keep both of them required and require that they're always set to the same value
 * keep both of them required and make sure that one is always more constrained if possible

in json-ld, do you have an idea as to what you would prefer to see?

**Comment by musicog** [comment]
I would propose making name required (I can't think of anything in the CE that we wouldn't want to have a human-legible label)

**Comment by musicog** [comment]
(sorry, accidental closure)
