### ISSUE TITLE
How to add ListItems to an ItemList

### ISSUE THREAD

**Issue by alastair** [trompamusic/ce-api#45]
I'm looking at the documentation to determine how to add a ListItem to an ItemList.
There is AddListItemNextItem, but this seems to be related to ordering items once they are already in a list.
It looks like we're missing the `itemListElement` field from https://schema.org/ItemList

**Comment by ChristiaanScheermeijer** [comment]
While it is defined in the [schema](https://github.com/trompamusic/ce-api/blob/staging/src/schema/type/ItemList.graphql#L39), I can't find it either in the GraphQL docs. We will investigate what the issue is.

**Comment by ChristiaanScheermeijer** [comment]
@alastair this mutation is now auto-generated:

```
mutation {
  AddItemListItemListElement(
    from: { identifier: "ItemListIdentifier" }
    to: { identifier: "ListItem/ThingIdentifier" }
  ) {
    from {
      identifier
    }
    to {
      identifier
    }
  }
}
```
