### ISSUE TITLE
Improve documentation for currently used node types

### ISSUE THREAD

**Issue by alastair** [trompamusic/ce-api#46]
The documentation for CreateEntryPoint and other mutations for the algorithm integration is lacking information. For example, I don't know what the fields contentType and encodingType should be. The documentation on schema.org (https://schema.org/EntryPoint) say 

contentType | Text | The supported content type(s) for an EntryPoint response.
encodingType | Text | The supported encoding type(s) for an EntryPoint request.

but this is just as confusing to me. Do the values have an effect on how the algorithm runs? In schema.org they're listed as Text, but in the example at https://github.com/trompamusic/ce-digital-score-edition-component#create-a-entrypoint they are lists of strings.

**Comment by ChristiaanScheermeijer** [comment]
@alastair I see your problem. Unfortunately, I don't have the answer either. We might be able to come to a solution by discussing this using this issue.

1) To answer your question `Do the values have an effect on how the algorithm runs`; No, the CE-API nor the algorithms should use these values. As a matter of fact, it only defines which content type the EntryPoint accepts and what content type it could possibly return when requesting. Given that the EntryPoint is an HTTP endpoint.

If we would follow the documentation strictly, the EntryPoint for an algorithm should be an accessible endpoint which can result in running an algorithm (`potentialAction`). Each algorithm could have its own EntryPoint or a single EntryPoint could manage multiple algorithms. Think of the EntryPoint deciding what to do based on the requests data or contentType.

2) The problem that I'm seeing is that schema.org doesn't make it clear whether properties should be scalar values or collections (not to my knowledge at least). The decision has been made to use collections over scalars, which I'm guessing, is based on this statement in the schema.org documentation: `The supported content type(s)`. However, this can also be interpreted as defining multiple content types comma separated.

Happy to hear your thoughts!

**Comment by baukef** [comment]
As discussed today we only need to write documentation for all types for M24.

**Comment by baukef** [comment]
This ends up in the GraphQL docs and in the D2.3

**Comment by ChristiaanScheermeijer** [comment]
@alastair can we close this issue in favour of the documentation at https://trompace-client.readthedocs.io/en/latest/index.html?

**Comment by alastair** [comment]
Yes, I think that's fine, keeping in mind that this documentation only covers the core types that we've been working with in detail in the project (see #82)
