### ISSUE TITLE
Release current staging on api-test

### ISSUE THREAD

**Issue by alastair** [trompamusic/ce-api#49]
Can we clear the database on api-test.trompamusic.eu and release the current staging branch? (I know that it doesn't have #48 yet, but we need to do some tests with @asarasua and need something more up-to-date than the current version)

**Comment by ChristiaanScheermeijer** [comment]
Hi @alastair, the test environment is actually using the latest commit from staging. However, I've just found out a lot of data is missing essential labels in the neo4j database. This is causing relational queries not working.

Are you sure that we can completely clear the database?

**Comment by alastair** [comment]
yes, deleting everything is fine, there are old items there from when we were still deciding the correct schema to use. I can recreate data using the most up-to-date schema if you clear it.

**Comment by ChristiaanScheermeijer** [comment]
`Deleted 17409 nodes, deleted 16123 relationships, completed after 322 ms.`

**Comment by alastair** [comment]
is #48 in staging?

**Comment by ChristiaanScheermeijer** [comment]
Yes, are you missing something?

**Comment by alastair** [comment]
not missing anything, I just wanted to confirm that the change from AddThingInterfaceThingInterface -> AddDigitalDocumentAudio and MergeDigitalDocumentAudio existed for all our types so that I can update my tools. thanks.
