### ISSUE TITLE
should you be able to query parent types

### ISSUE THREAD

**Issue by alastair** [trompamusic/ce-api#54]
after a discussion with Werner and David W at the Jan meeting

We have compositions added as MusicCompositions.

If you do a query for CreativeWork:
```query {
CreativeWork {
  identifier
}
}
```

You get no results back. As a hypothetical question, do we think that this query should also return all of the compositions? (and all other subclasses)

**Comment by ChristiaanScheermeijer** [comment]
I actually exclude interfaces from being autogenerated to queries here: https://github.com/trompamusic/ce-api/blob/staging/src/schema.js#L25

If we remove that, it becomes possible to run this query:

```graphql
query {
  CreativeWorkInterface {
    __typename
    identifier
  }
}
```

**Comment by ChristiaanScheermeijer** [comment]
@alastair do we expect that there will be CreativeWorks added to the CE? I would prefer using only the specific [subtypes](https://schema.org/CreativeWork#subtypes) and probably remove the CreativeWork type entirely.

**Comment by alastair** [comment]
We have no items in our schema that are only CreativeWorks. We should confirm with @musicog, but I think it's OK to remove it. As you said, we should be able to query all subclasses with something like
```graphql

query {
  CreativeWorkInterface {
    identifier
    ... on DigitalDocument {
       source
    }
    ... on MusicComposition {
        source
    }
  }
}
```

**Comment by musicog** [comment]
If there is an advantage to removing CreativeWorks from the CE, I agree that it should be of no consequence given our data model (and use of specialised types).

**Comment by ChristiaanScheermeijer** [comment]
The concrete `CreativeWork` type has been removed from the CE-API. It is possible to query on the `CreativeWorkInterface`.
