### ISSUE TITLE
Field describing node as with "restricted" access

### ISSUE THREAD

**Issue by demmyhonore** [trompamusic/ce-api#58]
E.g. for user performances.
A.S.
Choir

**Comment by alastair** [comment]
Performer usecase will have midi files from user performances. They will want to run algorithms, but the rehersal should be private until the user decides to publish it
@musicog

**Comment by alastair** [comment]
can we use `requiresSubscrition`?

**Comment by musicog** [comment]
This has been solved by our use of Solid Pods for user contributions
