### ISSUE TITLE
Query campaign manager status from CE

### ISSUE THREAD

**Issue by david-linssen** [trompamusic/ce-api#66]
To know when a Crowdsourced score is 'performable

added by MDW, relevant for Instrument & Orch case

**Comment by ChristiaanScheermeijer** [comment]
A running campaign is stored as **ControlAction** in the CE-API. This is the _identifier_ in the URL and can be used to query the status.

https://campaigns.trompamusic.eu/campaign/45568fb3-e55c-48d1-9103-fc6cb33d8b04

```graphql
query {
	ControlAction(identifier:"45568fb3-e55c-48d1-9103-fc6cb33d8b04") {
		identifier
		title
		actionStatus
	}
}
```

Which returns:

```
{
  "data": {
    "ControlAction": [
      {
        "identifier": "45568fb3-e55c-48d1-9103-fc6cb33d8b04",
        "title": "The campaign to rule them all v 2",
        "actionStatus": "PotentialActionStatus"
      }
    ]
  }
}
```

When the campaign has ended, the _actionStatus_ should be set to `CompletedActionStatus`. However, there is no mechanism or person assigned for this task. This should be done manually now by a person capable of determining that the score is "performable".
