### ISSUE TITLE
Production environment for CE API

### ISSUE THREAD

**Issue by baukef** [trompamusic/ce-api#78]

**Comment by baukef** [comment]
@alastair @musicog Unfortunately, we were not able to fully tackle authentication this week and we are wondering whether it is better to wait with the production release until we have authentication in place. What do you think/prefer?

**Comment by alastair** [comment]
I think you're right - the time we spent looking at the data modelling also shows us that we have to make some changes to the way that the data will be stored, so we need to work on that for another week or so as well before we get data into a production environment.

My only current concern is that if we push this back too much again then use-cases will delay their integration even further and it will be more difficult to integrate once we release the production environment.

**Comment by VincentCouzij** [comment]
The production environment is online and keys are send. I will close this issue.
