### ISSUE TITLE
Export additionalType as additional rdfs:types ("@type") in JSON-LD

### ISSUE THREAD

**Issue by musicog** [trompamusic/ce-api#85]
It would be useful if we could convert additionalType values into list additions to "@type" in the JSON-LD export of CE nodes. That is, ensure that the value for "@type" is a list that contains both the CE node's type, and any additionalTypes. 
 
(as discussed with @alastair)

**Comment by ChristiaanScheermeijer** [comment]
@alastair, this should be relatively easy to implement for all types. Are you planning to add this feature (it is currently marked in the deliverable as not implemented)

**Comment by alastair** [comment]
I'm going to add it to the annotation json-ld serialiser, but it could also be added to the generic one. I'll add it to my list.
