### ISSUE TITLE
Use standard-version for commit messages

### ISSUE THREAD

**Issue by ChristiaanScheermeijer** [trompamusic/ce-api#9]
We started this project using angular's commit message guidelines and conventional changelog in order to autogenerate the changelogs based on the commit messages. 

However, it seems that the angular preset is not being used by the conventional changelog command. I suggest we update to [standard-version](https://github.com/conventional-changelog/standard-version).

**Comment by alastair** [comment]
It would be nice to clarify this in the Readme, and also clarify how strongly we should adhere to eslint messages (I see you have been deleting a number of codacy messages, should we update eslintrc in this case?)

**Comment by ChristiaanScheermeijer** [comment]
> It would be nice to clarify this in the Readme

Yes, good idea.

>(I see you have been deleting a number of codacy messages, should we update eslintrc in this case?)

I've been removing the `Unnecessary block` errors which I've also turned off in the Codacy settings. `import { named } from 'dependency'` is fine in my opinion.
