### ISSUE TITLE
determine lifecycle of objects in the CE (created/updated)

### ISSUE THREAD

**Issue by alastair** [trompamusic/ce-api#94]
We are using dublin core in the CE, and therefore we have access to `dcterms:created`, which we can use to indicate when a node in the CE was created. This is useful for things like seeing if something should be updated (if we loaded metadata from MusicBrainz or Wikipedia and want to update it), or seeing when an Annotation was created.

In the case that something is modified (using the _Update_ mutations), do we also need to keep track of this somehow? I couldn't see any relevant types that we could use for this, and so I'm not sure what we should do.
Some options:
 - Change the 'created' field
 - Don't allow updates. If data has to be changed, make a new object and indicate somehow that the old one is out of date and there's now a new one
 - Is there some other standard for lifecycle of objects that allows us to tag when something was updated and who did it?

**Comment by alastair** [comment]
David pointed out dcterms:modified is what I was looking for, rather than 'updated'. For now I'll use this. There are some open questions to discuss about whether we use only dcelements, only dcterms, or some combination of the two.

**Comment by musicog** [comment]
See #96

**Comment by ChristiaanScheermeijer** [comment]
Should we close this issue in favour of #96?

**Comment by musicog** [comment]
Yes, I think this issue is duplicated in #96
