### ISSUE TITLE
Transition from dc elements to dc terms namespace

### ISSUE THREAD

**Issue by musicog** [trompamusic/ce-api#96]
Wim originally chose the (more constrained) dc elements namespace for formalisation of bibliographic properties in the CE schema. We are now bumping into the limitations of the 15 elements included therein; e.g. there exists a way to capture a generic "date", but not to differentiate between a "date created", a "date submitted", or a "date modified", which is emerging as a requirement. 

Given that the 15 elements are mirrored in the terms namespace, I propose a wholesale shift to dc terms from dc elements to avoid confusion. N.b. this comes with a side effect of greater semantic precision (dc terms specifies ranges for its descriptors), which also means that we would have to associate some additionalTypes with base schema.org classes -- e.g., schema:Persons will need to have additionalType dcterms:Agent to fulfil the requirements of dcterms:creator and dcterms:contributor. 

For now, I propose that we **shift the existing 15 elements to their terms equivalents, and introduce dcterms:created, dcterms:dateSubmitted, and dcterms:modified into the CE schema**. We can then add additional dcterms if and when they are required by specific use cases.

For background see `https://dublincore.org/specifications/dublin-core/dcmi-terms/#section-1`, particularly:

> The /terms/ namespace was originally created in 2001 for identifying new terms coined outside of the original fifteen-element Dublin Core. In 2008, in the context of defining formal semantic constraints for DCMI metadata terms in support of RDF applications, the original fifteen elements themselves were mirrored in the /terms/ namespace. As a result, there exists both a dc:date (http://purl.org/dc/elements/1.1/date) with no formal range and a corresponding dcterms:date (http://purl.org/terms/date) with a formal range of "literal". While these distinctions are significant for creators of RDF applications, most users can safely treat the fifteen parallel properties as equivalent. The most useful properties and classes of DCMI Metadata Terms have now been published as ISO 15836-2:2019 [ISO 15836-2:2019]. While the /elements/1.1/ namespace will be supported indefinitely, DCMI gently encourages use of the /terms/ namespace.

**Comment by ChristiaanScheermeijer** [comment]
Fixed with #121
